### ISSUE TITLE
Videos corrupted.

### ISSUE THREAD

**Issue by SonGokuSSJGOD** [proconsule/nxmp#6]
My videos were all of a sudden corrupted after a while of using this. Instead of playing an episode it will play the opening of the correct episode then decides to play a different episode all in that one video. On another one it would go all the way to the end on the video then stop there. Is anyone else having this problem?

**Comment by proconsule** [comment]
Local Playback/Usb Playback/Network playback? CFW type/version?
Can you give me more info. Thanks

**Comment by SonGokuSSJGOD** [comment]
Im not sure about local/usb/network playback but I'm putting it on my sd card sometimes via ftp and other times I take out the sd card. CFW 12.1.0/ version idk
