### ISSUE TITLE
Stable release ver

### ISSUE THREAD

**Issue by lowburger** [proconsule/nxmp#63]
Hi,

It was some months since NXMP v0.6.3 Rev 6(Nightly Build) pre-release and v0.6.2 was last stable release.

NXMP v0.6.3 Rev 6 pre-release is recommended? Thx

**Comment by Mymax74** [comment]
I don’t undestand how set nxmp for work with my zgemma,it’s possible e video tutorial to set my switch and deconder?
Please☺️

Inviato da iPhone

**Comment by darkxex** [comment]
Sure, the 6.3 rev 6 version, work amazing.

**Comment by lowburger** [comment]
> Sure, the 6.3 rev 6 version, work amazing.

@darkxex thx I use nightly some time and all seem fine
