### ISSUE TITLE
File browser is slow

### ISSUE THREAD

**Issue by gaozhilai** [proconsule/nxmp#65]
Hi, NXMP is an amazing video player in Nintendo Switch, thanks for what you do.
I found a performance issue. May you fix it in future version. There is some env info:

1) Nintendo Switch battery enhanced version
2) OS version 14.1.0|AMS 1.3.1|E
3) NXMP version [NXMP v0.6.3 Rev 6(Nightly Build)](https://github.com/proconsule/nxmp/releases/tag/v0.6.3_Rev6_Nightly)
4) After I play a few short videos, file browser becomes very slow until unresponsive, but the playback interface works fine

Looking forward to future releases. thanks again.

**Comment by proconsule** [comment]
0.7.0 Fix this also
