### ISSUE TITLE
Custom port source syntax

### ISSUE THREAD

**Issue by mightysashiman** [proconsule/nxmp#78]
Please add support for custom port number in source string syntax

For instance, using port 22222 as SFTP port could be specified as:
`source=TestSFTp|sftp://192.168.1.10:22222/path/ (without path it default to home)`

And add the relevant UI input to optionally specify port (and display that it falls back to default port XX (depending on protocol) if no port is specified

**Comment by proconsule** [comment]
Added in the todo list with high priority

**Comment by proconsule** [comment]
Done, it will be in the next stable release.
Code working and commited
