### ISSUE TITLE
Audio artifacts after sleep mode.

### ISSUE THREAD

**Issue by halop** [proconsule/nxmp#81]
Hello,

there is a bug in 0.7.0. and 0.8.0
Playback of mkv files works great,
but there is some crackling in the audio,
as soon as I turn the console in sleep mode and wake it up again.

It wasn't there in 0.6.3.

Thanks for your awesome work, it's the best player on the switch :-)

**Comment by proconsule** [comment]
Try Audren output with 0.8.1 and let me know

**Comment by halop** [comment]
that fixed it, thanks
