### ISSUE TITLE
[feature request] support webdav

### ISSUE THREAD

**Issue by zhu327** [proconsule/nxmp#88]
My videos are shared within the local network using the WebDAV protocol. So, can you support the WebDAV protocol?

**Comment by ZhouGe001** [comment]
你能使用http协议吗？我的也是webdav挂载阿里云盘，想用这个播放器的http试一试，但是没弄好。

**Comment by zhu327** [comment]
http://192.168.1.10/path/

不能挂载根目录, 要指定path

**Comment by proconsule** [comment]
I am sorry but i am italian, i dont speak chinese

**Comment by proconsule** [comment]
If i translated well with google, yes a path is mandatory at the moment.
